<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container34clah9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container34clah9/appProdProjectContainer.php') {
    touch(__DIR__.'/Container34clah9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container34clah9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container34clah9\appProdProjectContainer(array(
    'container.build_hash' => '34clah9',
    'container.build_id' => '1473cf62',
    'container.build_time' => 1546551124,
), __DIR__.\DIRECTORY_SEPARATOR.'Container34clah9');
