<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ3ylpdr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ3ylpdr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJ3ylpdr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJ3ylpdr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerJ3ylpdr\appDevDebugProjectContainer(array(
    'container.build_hash' => 'J3ylpdr',
    'container.build_id' => 'cd1aebb6',
    'container.build_time' => 1546551661,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ3ylpdr');
